app:
  save-to-file: true
  database-location: db

spring:
  profiles:
    default: prod
  application:
    name: TheDB

#logging:
#  structured:
#    format:
#      console: ecs

server:
  port: 8080
